1653031350643	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1653031601616	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1653031602012	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1653031602012	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1653031602014	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1653031604459	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1653031604812	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1653031604812	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1653031604814	Sync.Service	DEBUG	User-Agent: Firefox/100.0.1 (Intel Mac OS X 10.15) FxSync/1.102.0.20220513165813.desktop
1653031604814	Sync.Service	INFO	Starting sync at 2022-05-20 09:26:44 in browser session TNYIjW4_e4xL
1653031604814	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1653031604818	Sync.Status	INFO	Resetting Status.
1653031604818	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1653031604819	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1653031604819	FirefoxAccounts	DEBUG	getOAuthToken enter
1653031604819	FirefoxAccounts	TRACE	getCachedToken returning cached token
1653031604819	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1653031604820	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1653031611413	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1653031611529	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1653031611529	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1653031611529	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1653031611530	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1653031611530	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1653031611532	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
