1652429997707	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1652430124791	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1652430125276	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1652430125276	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1652430125278	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1652430125476	Sync.SyncScheduler	DEBUG	Woke from sleep.
1652430125477	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1652430125478	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1652430125478	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1652430127392	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1652430127480	Sync.Service	DEBUG	User-Agent: Firefox/100.0 (Intel Mac OS X 10.15) FxSync/1.102.0.20220428192727.desktop
1652430127480	Sync.Service	INFO	Starting sync at 2022-05-13 10:22:07 in browser session -Yrw3OYMS4jx
1652430127480	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1652430127482	Sync.Status	INFO	Resetting Status.
1652430127482	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1652430127483	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1652430127483	FirefoxAccounts	DEBUG	getOAuthToken enter
1652430127483	FirefoxAccounts	TRACE	getCachedToken returning cached token
1652430127483	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1652430127484	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1652430127490	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1652430127490	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1652430127490	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1652430127490	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1652430127491	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1652430127493	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
